local files = {
    -- "sha1.lua",
    "Items/postload.lua",
    "Items/helpers.lua",
    "Items/overrides.lua",
    "Items/rarity_definitions.lua",
    "Items/colour_definitions.lua",
    "Items/render.lua",
    "Items/badges.lua",
    "Items/hand_buffs.lua",
    "Items/text_effects.lua",
    "Items/operator_stuff.lua",
    "Items/configui.lua",
    "Items/credits_ui.lua",
    "Items/recommended.lua",
    "Items/ante.lua",
    "Items/hands.lua",
    "Items/metaprogression.lua",
    "Items/Jokers/tau.lua",
    "Items/Jokers/tau/tau_common.lua",
    "Items/Jokers/tau/tau_uncommon.lua",
    "Items/Jokers/tau/tau_rare.lua",
    "Items/Jokers/tau/tau_legendary.lua",
    "Items/Consumables/spectral.lua",
    "Items/Consumables/tau_spectrals.lua",
    "Items/Consumables/tarot.lua",
    "Items/Consumables/planetoids.lua",
    "Items/Consumables/superplanets.lua",
    "Items/Consumables/cataclysm.lua",
    "Items/Consumables/aesthetic.lua",
    "Items/boosters.lua",
    "Items/Jokers/animation.lua",
    "Items/Jokers/common.lua",
    "Items/Jokers/uncommon.lua",
    "Items/Jokers/rare.lua",
    "Items/Jokers/renowned.lua",
    "Items/Jokers/legendary.lua",
    "Items/Jokers/aesthetijokers.lua",
    "Items/Jokers/exquisite.lua",
    "Items/Jokers/prestigious.lua",
    "Items/blinds.lua",
    "Items/tags.lua",
    "Items/decks.lua",
    "Items/sleeves.lua",
    "Items/vouchers.lua",
    "Items/enhancements.lua",
    "Items/seals.lua",
    "Items/editions.lua",
    "Items/globalcalc.lua",
    "Items/stickers.lua",
    "Items/challenges.lua",
    "Items/quips.lua",
    "Items/deckskin.lua",
}

for i,dir in ipairs(files) do
    print("Vallkarri: Loading " .. dir)
    assert(SMODS.load_file(dir, "vallkarri"))()
end

-- assert(SMODS.load_file("", "vallkarri"))()